### ISSUE TITLE
Suggestions cuz why not

### ISSUE THREAD

**Issue by iusemeteor** [XboxDevStore/XboxDevStore.github.io#8]
Port Java so that I can play Minecraft at 1000 fps
Port Cemu Emulator (open source)
Port Yuzu Emulator (open source)
Port Chrome Browser to make it more accessible to users who don't have another pc. (Chromium is open src)

**Comment by iusemeteor** [comment]
Also fix the discord invite link pls

**Comment by SternXD** [comment]
I can fix the discord invite link but none of the other things will happen for a while.
